import { createFileRoute, Link } from "@tanstack/react-router";
import { AirVent, Droplets, HousePlug, Scale } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ContactBand, PageHero } from "@/components/site-layout";
import technicianImage from "@/assets/regisclim-technician.jpg";

export const Route = createFileRoute("/installation-de-climatisation-a-nimes")({
  head: () => ({ meta: [{ title: "Installation de climatisation à Nîmes — RegisClim" }, { name: "description", content: "Installation de climatisation, pompe à chaleur, gainable et chauffe-eau thermodynamique à Nîmes." }, { property: "og:title", content: "Installation de climatisation à Nîmes — RegisClim" }, { property: "og:description", content: "Une installation étudiée et réalisée par un professionnel qualifié." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/installation-de-climatisation-a-nimes" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/installation-de-climatisation-a-nimes" }] }), component: InstallationPage,
});

const equipment = [
  { icon: AirVent, title: "Pompe à chaleur réversible", text: "Un système ingénieux qui transfère les calories de l’extérieur vers l’intérieur. Il rafraîchit en été et chauffe en hiver tout en limitant la consommation d’énergie." },
  { icon: HousePlug, title: "Pompe à chaleur air-eau", text: "Elle peut assurer le chauffage et l’eau chaude sanitaire. Adaptée au neuf comme à la rénovation, elle réinjecte l’énergie captée dans le circuit du logement." },
  { icon: Scale, title: "Climatisation gainable", text: "Une solution réversible, discrète et centralisée. L’unité et les gaines sont dissimulées dans les combles ou un faux-plafond ; seules les grilles restent visibles." },
  { icon: Droplets, title: "Chauffe-eau thermodynamique", text: "Un ballon d’eau chaude associé à une pompe à chaleur qui capte les calories de l’air pour réduire votre consommation énergétique." },
];

function InstallationPage() { return <><PageHero eyebrow="Étude & pose" title="Installation de climatisation à Nîmes">Régis Garnier installe des climatisations chez les particuliers et les professionnels à Nîmes et ses environs.</PageHero><section className="content-shell"><div className="grid gap-12 lg:grid-cols-[1fr_1.1fr]"><div><img src={technicianImage} loading="lazy" width={1200} height={900} alt="Installation professionnelle d’une climatisation" className="aspect-[4/3] w-full object-cover" /><aside className="mt-5 border-l-4 border-accent bg-muted p-6 text-sm leading-7 text-muted-foreground">Le Code de l’environnement prévoit que seul un professionnel habilité peut mettre une climatisation en service.</aside></div><div className="prose-copy"><p className="eyebrow text-primary">Réglementation</p><h2 className="mt-3!">Une solution adaptée à chaque lieu</h2><p>L’installation d’une climatisation exige un spécialiste qualifié. À la maison, au bureau ou dans un magasin, l’objectif est d’apporter confort et bien-être en respectant les contraintes techniques, l’esthétique et le bon dimensionnement.</p><p>Après une expertise technique de votre logement ou local, Régis Garnier vous propose la solution la plus adaptée. Il reste votre interlocuteur unique pour simplifier tous les échanges.</p></div></div><div className="mt-16 grid gap-px bg-border md:grid-cols-2">{equipment.map(({icon:Icon,title,text})=><article key={title} className="bg-background p-8"><Icon className="size-8 text-primary"/><h2 className="mt-5 font-display text-2xl font-extrabold">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{text}</p></article>)}</div><div className="mt-12 text-center"><h2 className="font-display text-3xl font-extrabold">C’est un de vos futurs projets ?</h2><p className="mx-auto mt-3 max-w-2xl text-muted-foreground">Découvrez les aides disponibles pour concrétiser votre installation.</p><Button asChild size="hero" className="mt-6"><Link to="/aides-et-subventions">Je découvre mes aides</Link></Button></div></section><ContactBand /></> }